name: CI

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
jobs:
  calculate-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.0.0"
      - uses: fatton139/pr-comment-file-size@main
        with:
          dist_path: "packages/crop/dist"
          update_comment: false
          token: ${{ secrets.GITHUB_TOKEN }}
